spring:
  web:
    resources:
      cache:
        period: 666
      add-mappings: true
  mvc:
    view:
      prefix: /
      suffix: .html
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: false
server:
  port: 8088
