spring:
  web:
    resources:
      cache:
        period: 666
      add-mappings: true
  mvc:
    view:
      prefix: /
      suffix: .html
  thymeleaf:
    mode: html
    cache: false
    encoding: utf-8
  devtools:
    restart:
      enabled: true
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: false
server:
  port: 8088
